### PR TITLE
Fix promise when reading from Atlas

### PR DESCRIPTION
**Pull request by am-MongoDB**

### CODE REVIEW

**Comment by aydrian** [comment]
What are you making this change to the master branch? This should be left as is so the person doing the exercise can do it.

**Comment by am-MongoDB** [comment]
So is the promise code intentionally broken in the master branch?

**Comment by aydrian** [comment]
Define broken? It returns a promise that resolves to an array of entries. It is mocked in the master branch. There is an exercise to replace that mock.

**Comment by am-MongoDB** [comment]
Let me check again exactly where the issue was. I know that when I followed the instructions (including the suggested change), it stopped working.

**Comment by am-MongoDB** [comment]
My mistake – code is good as-is

**Pull request closed without merging**
